In [48]:
import numpy as np
import numba
import math 


In [149]:
n=21

In [21]:
phi=(math.sqrt(5)-1)/2

In [143]:
exponents_list=list(range(0,20+1))

In [144]:
exponents=np.array(exponents_list)

In [145]:
print(exponents.T)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [146]:
a = np.zeros(shape=(21,1))

In [147]:
print(a)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [150]:
for i in range(n):
    print(exponents[i])

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [151]:
for i in range(n):
    [a[i]]=[phi ** exponents[i]]
print(a)

[[1.00000000e+00]
 [6.18033989e-01]
 [3.81966011e-01]
 [2.36067977e-01]
 [1.45898034e-01]
 [9.01699437e-02]
 [5.57280900e-02]
 [3.44418537e-02]
 [2.12862363e-02]
 [1.31556175e-02]
 [8.13061876e-03]
 [5.02499874e-03]
 [3.10562002e-03]
 [1.91937873e-03]
 [1.18624129e-03]
 [7.33137436e-04]
 [4.53103854e-04]
 [2.80033582e-04]
 [1.73070272e-04]
 [1.06963310e-04]
 [6.61069614e-05]]


In [154]:
b = np.zeros(shape=(21,1))

In [156]:
print(b)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [160]:

for i in range(n):
    if i<2: 
        [b[i]]= [phi ** i]
    else:
        #[recursion[i]]= [phi ** i-2 - phi ** i-1]
        [b[i]]= [b[i-2]-b[i-1]]
print(b)


[[1.00000000e+00]
 [6.18033989e-01]
 [3.81966011e-01]
 [2.36067977e-01]
 [1.45898034e-01]
 [9.01699437e-02]
 [5.57280900e-02]
 [3.44418537e-02]
 [2.12862363e-02]
 [1.31556175e-02]
 [8.13061876e-03]
 [5.02499874e-03]
 [3.10562002e-03]
 [1.91937873e-03]
 [1.18624129e-03]
 [7.33137436e-04]
 [4.53103854e-04]
 [2.80033582e-04]
 [1.73070272e-04]
 [1.06963311e-04]
 [6.61069610e-05]]


In [159]:
a-b

array([[ 0.00000000e+00],
       [ 0.00000000e+00],
       [ 1.11022302e-16],
       [-5.55111512e-17],
       [ 2.22044605e-16],
       [-2.35922393e-16],
       [ 4.64905892e-16],
       [-6.86950496e-16],
       [ 1.15532584e-15],
       [-1.83707216e-15],
       [ 2.99413272e-15],
       [-4.82947016e-15],
       [ 7.82533760e-15],
       [-1.26545909e-14],
       [ 2.04805790e-14],
       [-3.31349531e-14],
       [ 5.36156406e-14],
       [-8.67504853e-14],
       [ 1.40366126e-13],
       [-2.27116557e-13],
       [ 3.67482710e-13]])