In [80]:
import numpy as np

In [111]:
n=8

In [112]:
a=1
b=100000

In [113]:
lst=list(range(1,9))

In [114]:
print(lst)

[1, 2, 3, 4, 5, 6, 7, 8]


In [115]:
lst_array=np.array(lst)

In [116]:
c=np.zeros(shape=(8,1))

In [117]:
print(c)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [118]:
for i in range(n):
    [c[i]]=[np.float_power(10, -lst_array[i])]
print(c)

[[1.e-01]
 [1.e-02]
 [1.e-03]
 [1.e-04]
 [1.e-05]
 [1.e-06]
 [1.e-07]
 [1.e-08]]


In [120]:
q=np.zeros(shape=(8,1))

In [121]:
print(q)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [129]:
def quadratic_function(c):
    return 1/2 * (-b + np.sign(b) * np.sqrt(b**2 - 4*a*c))

In [131]:
for i in range(n):
    [q[i]]=[quadratic_function(c[i])]
print(q)

[[-1.00000034e-06]
 [-1.00000761e-07]
 [-9.99716576e-09]
 [-1.00408215e-09]
 [-1.01863407e-10]
 [-7.27595761e-12]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]


In [132]:
x_1=np.zeros(shape=(8,1))

In [133]:
for i in range(n):
    [x_1[i]]=[q[i]/a]
print(x_1)

[[-1.00000034e-06]
 [-1.00000761e-07]
 [-9.99716576e-09]
 [-1.00408215e-09]
 [-1.01863407e-10]
 [-7.27595761e-12]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]


In [134]:
x_2=np.zeros(shape=(8,1))

In [135]:
for i in range(n):
    [x_2[i]]=[c[i]/q[i]]
print(x_2)

[[ -99999.96614644]
 [ -99999.23855646]
 [-100028.3504163 ]
 [ -99593.44454493]
 [ -98170.68105143]
 [-137438.953472  ]
 [             inf]
 [             inf]]


C:\Users\bayle\AppData\Local\Temp\ipykernel_11824\3871057776.py:2: RuntimeWarning: divide by zero encountered in divide
  [x_2[i]]=[c[i]/q[i]]


In [136]:
def quadratic_equation():
    return 1/2 * (-b + b * np.sqrt(b**2 - 4*a*c))

In [140]:
aux = np.sqrt(b**2-4*a*c)
print(aux)

[[ 99999.999998  ]
 [ 99999.9999998 ]
 [ 99999.99999998]
 [100000.        ]
 [100000.        ]
 [100000.        ]
 [100000.        ]
 [100000.        ]]


In [137]:
solution=np.zeros(shape=(8,1))

In [138]:
for i in range(n):
    [solution[i]]=[quadratic_function(c[i])]
print(solution)

[[-1.00000034e-06]
 [-1.00000761e-07]
 [-9.99716576e-09]
 [-1.00408215e-09]
 [-1.01863407e-10]
 [-7.27595761e-12]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]


In [139]:
solution-x_1

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])